name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels: "fix"
  - title: "🔥 Hot Fixes"
    label: "hotfix"
  - title: "🚅 Performance"
    label: "performance"
  - title: "😎 Refactor"
    label: "refactor"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Backend

  # v$RESOLVED_VERSION	

  ## What Changed

  $CHANGES
