name: "Lint PR"

permissions:
  pull-requests: read

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validatePrTitle:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
