name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/release-drafter/release-drafter
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          # With publish: false, the draft release will be created but not published.
          # If true, the draft release will be published immediately - we need to do this manually, so we will keep the publish feature to false.
          publish: false
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.SRE_GITHUB_ACCESS_TOKEN }}{% endraw %}
