# Author: Philip De Lorenzo <phil.delorenzo@manscaped.com>
# Date: 2025-03-01
# This is the main entrypoint for the SRE Core Apps (Receiver) workflow
# This workflow is responsible for deploying the core apps to GCP
name: SRE - Actions (Entrypoint)

on:
  push:
    branches:
      - '*' # All branches

  pull_request:
    branches:
      - 'main'
      - 'master'

    types: [opened, synchronize, reopened, closed]

jobs:
    # This step will return the environment based on pull_request or workflow_call
    # If this is a push, or pull_request, we will set the environment to dev
    # If this is a workflow_call, we will set the environment to the input value
    set-environment:
      runs-on: ubuntu-latest
      outputs:
        environment: ${{ steps.set-environment.outputs.environment }}
      steps:
        - name: Set Environment
          id: set-environment
          run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                echo "environment=dev" >> $GITHUB_OUTPUT
            else
                echo "We don't need to set an environment if this is simply a push event, we will NOT be deploying it..."
            fi

    # Let's get the branch name (Branches are different for PRs and pushes)
    call-branch:
        uses: ./.github/workflows/sre-current-branch.yml
        secrets:
            SRE_GITHUB_ACCESS_TOKEN: ${{ secrets.SRE_GITHUB_ACCESS_TOKEN }}

    # If this is a github pull_request, and it is merged, then we want to run the release drafter
    call-test:
      runs-on: ubuntu-latest
      needs: [set-environment]
      steps:
        - name: Check if this is a pull request
          id: check-pull-request
          run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                echo "This is a pull request"
                echo "is_pull_request=true" >> $GITHUB_OUTPUT
            else
                echo "This is not a pull request"
                echo "is_pull_request=false" >> $GITHUB_OUTPUT
            fi

            echo "${{ github.event_name }}"
            echo "${{ github.event.action }}"
            echo "${{ github.event.pull_request.merged }}"

    call-release-drafter:
      if: github.event.pull_request.merged == true
      needs: [call-branch]
      uses: ./.github/workflows/sre-release-drafter.yml
      secrets:
        SRE_GITHUB_ACCESS_TOKEN: ${{ secrets.SRE_GITHUB_ACCESS_TOKEN }}
